Add installation guide
pwntester/ysoserial.net pull request #100
Opened 2021-01-01 07:17 UTC by shelld3v

Many people are installing this by: `git clone https://github.com/pwntester/ysoserial.net`

2021-01-01 16:58 UTC, pwntester requested changes
Thanks for the typo fix! I dont think we need individual download links for old versions though

2021-01-01 16:58 UTC, pwntester commented on README.md
> +You can install the software from this page: https://github.com/pwntester/ysoserial.net/releases
```suggestion
You can install the latest version and previous releases of YSoSerial.NET from [the releases page](https://github.com/pwntester/ysoserial.net/releases)
```

2021-01-01 16:58 UTC, pwntester commented on README.md
> +
```suggestion
```

2021-01-02 05:05 UTC, shelld3v commented
Hi, I think that many people are so familiar with `git clone`, so they may don't know what to do on the releases page (there are notes, source codes, ...), I used to be like this. So it's maybe better to include the download links in the README page!

2021-01-07 11:19 UTC, pwntester requested changes

2021-01-07 11:19 UTC, pwntester commented on README.md
> +
```suggestion
- Release 1.34 (latest version): [Download](https://github.com/pwntester/ysoserial.net/releases/download/v1.34/ysoserial-1.34.zip)

```

2021-01-07 11:35 UTC, pwntester approved these changes

2021-01-07 11:35 UTC, merged

2021-01-07 11:35 UTC, pwntester commented
thanks!